source "https://rubygems.org"

gem "rails",        "4.2.6"
gem "sprockets",    "3.6.3"
gem "bcrypt",       "3.1.7"
gem "faker",        "1.4.2"
gem "config"
gem "sass-rails",   "5.0.2"
gem "uglifier",     "2.5.3"
gem "coffee-rails", "4.1.0"
gem "jquery-rails", "4.0.3"
gem "turbolinks",   "2.3.0"
gem "jbuilder",     "2.2.3"
gem "bootstrap-sass", "3.2.0.0"
gem "sdoc",         "0.4.0", group: :doc
gem "devise"
gem "cancancan"
gem "whenever"
gem "sidekiq"
gem "kaminari"
gem "bootstrap-kaminari-views"
gem "ransack"
gem "carrierwave"
gem "omniauth-twitter"
gem "omniauth-facebook"
gem "omniauth-google-oauth2"
gem "figaro"
gem "bootstrap-glyphicons"
gem "simple_form"
gem "friendly_id", "~> 5.1.0"
gem "social-share-button"

group :development, :test do
  gem "sqlite3",     "1.3.9"
  gem "byebug",      "3.4.0"
  gem "web-console", "2.0.0.beta3"
  gem "spring",      "1.1.3"
  gem "pry-rails"
  gem "rspec-rails", "~> 3.0"
  gem "rspec-collection_matchers"
  gem "factory_girl_rails", "~> 4.0"
  gem "capybara"
  gem "simplecov", require: false
  gem "shoulda-matchers", "~> 3.1"
  gem "database_cleaner"
end

group :production do
  gem "pg",             "0.17.1"
  gem "rails_12factor", "0.0.2"
end
